name: Training Pipeline

on:
  schedule:
    - cron: "0 0 * * *"   # har din raat 12 baje (UTC) chalega
  workflow_dispatch:        # manual trigger ke liye bhi

jobs:
  run-training-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python training_pipeline.py